[package]
name = "tf2rs"
version = "0.1.0"
authors = ["ldesgoui <ldesgoui@gmail.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]
libc = "0.2.35"
goblin = "0.0.13"
cpp_demangle = "0.2.7"
lazy_static = "1.0.0"
